spring:
  application:
    name: vaarahidesigns
  datasource:
    url: jdbc:postgresql://localhost:5432/vaarahidesigns
    username: abdulafroz0001
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
