server:
  port: 8000
spring:
  application:
    name: vaarahidesigns
  datasource:
    url: jdbc:postgresql://localhost:5431/vaarahidesigns
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
